name: Convert CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Convert Executable
        run: make

      - name: Upload Convert Executable
        uses: actions/upload-artifact@v4
        with:
          name: convert
          path: ./convert

      - name: Build Test Executable with Coverage
        run: make ctest

      - name: Run Test Script and Generate Coverage Report
        run: |
          chmod +x ./test_script.sh
          ./test_script.sh > test_results.txt
          gcov ctest

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: ./test_results.txt

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: ./*.gcov

