name: CI - Test ctest Utility


on:  
  push:  
    branches: [ "main" ]  

jobs:  
  test:  
    runs-on: ubuntu-latest  

    steps:  
      - uses: actions/checkout@v4  

      - name: Test
        run: make ctest; ./test_script >test_results.txt; gcov ctest-convert.c ctest-parse_options.c ctest-main.c
          

      - name: Upload Test Results  
        if: ${{ always() }} 
        uses: actions/upload-artifact@v4  
        with:
          name: Test Results  
          path: ./test_results.txt  
