name: CI - Test ctest Utility

on:  
  push:  
    branches: [ "main" ]  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  

      - name: Build and Run Tests
        run: |
          make clean               # Clean previous builds
          make ctest               # Build the executable
          ./ctest > test_results.txt  # Run the tests and save results
          gcov main.c convert.c parse_options.c  # Generate coverage files

      - name: Upload Test Results  
        if: ${{ always() }} 
        uses: actions/upload-artifact@v2  
        with:
          name: Test Results  
          path: ./test_results.txt  
