name: CI - Test ctest Utility

on:  
  push:  
    branches: [ "main" ]  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4

      - name: Build and Run Tests
        run: |

          # Clean previous builds
          make clean       

          # Build the executable        
          make ctest 

          # Run the tests and save results
          ./ctest > test_results.txt  

          # Generate coverage files
          gcov main.c convert.c parse_options.c  

      - name: Upload Test Results  
        if: ${{ always() }} 
        uses: actions/upload-artifact@v4
        with:
          name: Test Results  
          path: ./test_results.txt  

